import { useState, type FC } from "react";
import { useNavigate } from "react-router-dom";
import type { MeshContext } from "../types/mesh";

interface SecurityIntelligenceHeroProps {
  ctx?: MeshContext;
}

interface BannerConfig {
  icon: string;
  label: string;
  bg: string;
  border: string;
  text: string;
}

const BANNER: Record<string, BannerConfig> = {
  APPROVE: {
    icon: "\u2713",
    label: "APPROVED FOR DEPLOYMENT",
    bg: "bg-green-900/20",
    border: "border-green-700",
    text: "text-green-400",
  },
  APPROVE_WITH_MONITORING: {
    icon: "\u26A0",
    label: "APPROVED WITH MONITORING",
    bg: "bg-yellow-900/20",
    border: "border-yellow-700",
    text: "text-yellow-400",
  },
  ESCALATE_REVIEW: {
    icon: "\u2716",
    label: "ESCALATION REQUIRED",
    bg: "bg-red-900/20",
    border: "border-red-700",
    text: "text-red-400",
  },
  ESCALATION_REQUIRED: {
    icon: "\u2716",
    label: "ESCALATION REQUIRED",
    bg: "bg-red-900/20",
    border: "border-red-700",
    text: "text-red-400",
  },
  BLOCK: {
    icon: "\u2716",
    label: "BLOCKED",
    bg: "bg-red-900/20",
    border: "border-red-700",
    text: "text-red-400",
  },
};

const modelLabels: Record<string, string> = {
  blue: "Blue Agent",
  red: "Red Agent",
  security_intelligence: "Security Intelligence Agent",
};

const modelAbbr: Record<string, string> = {
  blue: "BLUE",
  red: "RED",
  security_intelligence: "Security Intelligence",
};

const modelColors: Record<string, string> = {
  blue: "border-blue-900/50 bg-blue-900/20 text-blue-400",
  red: "border-red-900/50 bg-red-900/20 text-red-400",
  security_intelligence: "border-purple-900/50 bg-purple-900/20 text-purple-400",
};

const AgentBadge: FC<{ agent: "blue" | "red" | "security_intelligence"; model: string }> = ({
  agent,
  model,
}) => (
  <span
    className={`inline-flex items-center gap-1.5 rounded border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${modelColors[agent]}`}
  >
    <span>{modelAbbr[agent]}</span>
    <span className="font-normal normal-case text-[#9ca3af]">
      {model.split("/").pop() ?? model}
    </span>
  </span>
);

const SecurityIntelligenceHero: FC<SecurityIntelligenceHeroProps> = ({ ctx }) => {
  const navigate = useNavigate();
  const [reasoningOpen, setReasoningOpen] = useState(false);
  const report = ctx?.security_report;
  const models = ctx?.active_models;
  const hasExploits = (report?.verified_exploits ?? 0) > 0;

  if (!report) {
    return (
      <div className="rounded-xl border border-[#1f2937] bg-[#111827] p-6 shadow-lg">
        <h2 className="mb-2 text-lg font-semibold text-[#f3f4f6]">
          AegisMesh Security Intelligence Assessment
        </h2>
        <p className="text-sm text-[#9ca3af]">
          Run a mesh to generate a Security Intelligence assessment.
        </p>
      </div>
    );
  }

  const bannerKey =
    report.deployment_recommendation in BANNER
      ? report.deployment_recommendation
      : "BLOCK";
  const banner = BANNER[bannerKey];

  const agentItems = [
    {
      key: "blue",
      label: "Blue Agent",
      status: ctx?.latest_patch ? "Patch Generated" : "Pending",
      ok: !!ctx?.latest_patch,
      color: "text-blue-400",
    },
    {
      key: "red",
      label: "Red Agent",
      status: ctx?.audit_history && ctx.audit_history.length > 0 ? "Audit Complete" : "Pending",
      ok: !!(ctx?.audit_history && ctx.audit_history.length > 0),
      color: "text-red-400",
    },
    {
      key: "security_intelligence",
      label: "Security Intelligence",
      status: "Assessment Complete",
      ok: true,
      color: "text-purple-400",
    },
  ];

  return (
    <div className="rounded-xl border border-[#1f2937] bg-[#111827] shadow-lg">
      {/* 1. Decision Banner */}
      <div
        className={`flex items-center justify-between rounded-t-xl border-b px-6 py-4 ${banner.bg} ${banner.border}`}
      >
        <div className={`flex items-center gap-3 ${banner.text}`}>
          <span className="text-2xl font-bold">{banner.icon}</span>
          <span className="text-lg font-bold tracking-wider">{banner.label}</span>
        </div>
        <span
          className={`rounded-lg border px-3 py-1 text-xs font-semibold uppercase tracking-wider ${banner.bg} ${banner.border} ${banner.text}`}
        >
          {report.deployment_recommendation}
        </span>
      </div>

      <div className="space-y-4 p-6">
        {/* 2. Header */}
        <div className="flex items-start justify-between">
          <div>
            <h2 className="text-2xl font-bold tracking-tight text-[#f3f4f6]">
              AegisMesh Security Intelligence Assessment
            </h2>
            {models?.security_intelligence && (
              <p className="mt-1 text-sm text-[#6b7280]">
                Generated by{" "}
                <span className="text-[#9ca3af]">{models.security_intelligence}</span>
              </p>
            )}
          </div>
          {models?.security_intelligence && (
            <AgentBadge agent="security_intelligence" model={models.security_intelligence} />
          )}
        </div>

        {/* 3. Agent Workflow Snapshot */}
        <div className="flex flex-wrap items-stretch gap-0 rounded-lg border border-[#1f2937] bg-[#0a0f1a]">
          {agentItems.map((item, idx) => (
            <div key={item.key} className="flex flex-1 items-center gap-2.5 px-4 py-2.5 min-w-[130px]">
              <span
                className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${
                  item.ok
                    ? item.key === "blue"
                      ? "bg-blue-900/60 text-blue-400"
                      : item.key === "red"
                        ? "bg-red-900/60 text-red-400"
                        : "bg-purple-900/60 text-purple-400"
                    : "bg-gray-900/60 text-gray-500"
                }`}
              >
                {item.ok ? "\u2713" : "\u25CB"}
              </span>
              <div className="min-w-0">
                <div className="truncate text-[10px] font-semibold uppercase tracking-wider text-[#6b7280]">
                  {item.label}
                </div>
                <div className={`truncate text-xs font-semibold ${item.ok ? item.color : "text-gray-500"}`}>
                  {item.status}
                </div>
              </div>
              {idx < agentItems.length - 1 && (
                <div className="ml-auto w-px self-stretch bg-[#1f2937]" />
              )}
            </div>
          ))}
        </div>

        {/* 4. Security Score */}
        <div
          className={`flex flex-col items-center justify-center rounded-xl border py-5 ${
            report.risk_level === "LOW"
              ? "border-green-900/50 bg-[#0a3b0a] shadow-lg shadow-green-900/20"
              : report.risk_level === "MEDIUM"
                ? "border-yellow-900/50 bg-[#3b3b0a] shadow-lg shadow-yellow-900/20"
                : report.risk_level === "HIGH"
                  ? "border-orange-900/50 bg-[#3b2a0a] shadow-lg shadow-orange-900/20"
                  : "border-red-900/50 bg-[#3b0a0a] shadow-lg shadow-red-900/20"
          }`}
        >
          <div className="text-7xl font-black tracking-tight text-[#f3f4f6]">
            {report.security_score}
          </div>
          <div className="mt-1.5 text-xs font-bold uppercase tracking-[0.2em] text-[#9ca3af]">
            Security Score
          </div>
          <span
            className={`mt-1.5 rounded-full px-4 py-1 text-xs font-bold uppercase tracking-wider ${
              report.risk_level === "LOW"
                ? "bg-green-900/60 text-green-400"
                : report.risk_level === "MEDIUM"
                  ? "bg-yellow-900/60 text-yellow-400"
                  : report.risk_level === "HIGH"
                    ? "bg-orange-900/60 text-orange-400"
                    : "bg-red-900/60 text-red-400"
            }`}
          >
            {report.risk_level} Risk
          </span>
        </div>

        {/* 5. Agent Models */}
        {models && (
          <div>
            <h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-[#9ca3af]">
              Agent Models
            </h4>
            <div className="grid grid-cols-3 gap-3">
              {(["blue", "red", "security_intelligence"] as const).map((key) => (
                <div
                  key={key}
                  className={`rounded-lg border bg-[#0a0f1a] p-3 ${modelColors[key].split(" ")[0]}`}
                >
                  <div className="text-xs font-medium uppercase tracking-wider text-[#6b7280]">
                    {modelLabels[key]}
                  </div>
                  <div className="mt-1 truncate text-sm font-medium text-[#f3f4f6]">
                    {models[key]}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* 6. BAND Agent Collaboration */}
        <div className="rounded-lg border border-[#1f2937] bg-[#111827] p-3">
          <div className="mb-2 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span
                className={`inline-block h-2 w-2 rounded-full ${ctx?.session_id ? "bg-[#22c55e]" : "bg-[#4b5563]"}`}
              />
              <span className="text-xs font-semibold uppercase tracking-wider text-[#9ca3af]">
                BAND Agent Collaboration
              </span>
            </div>
            {ctx?.session_id && (
              <button
                type="button"
                onClick={() => navigate(`/transcript/${ctx.session_id}`)}
                className="inline-flex items-center gap-1.5 rounded-lg border border-[#22c55e]/30 bg-[#22c55e]/10 px-3 py-1 text-xs font-semibold text-[#22c55e] transition-colors hover:bg-[#22c55e]/20"
              >
                View BAND Transcript &rarr;
              </button>
            )}
          </div>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[#6b7280]">
            {ctx?.band_room_id && (
              <span className="font-mono">
                Room: {ctx.band_room_id.length > 16
                  ? ctx.band_room_id.slice(0, 16) + "..."
                  : ctx.band_room_id}
              </span>
            )}
            {ctx?.band_telemetry && (
              <>
                <span>
                  Messages mirrored: {ctx.band_telemetry.band_messages_sent}
                </span>
                {ctx.band_telemetry.band_failures > 0 && (
                  <span className="text-[#ef4444]">
                    Failures: {ctx.band_telemetry.band_failures}
                  </span>
                )}
              </>
            )}
            {!ctx?.session_id && (
              <span className="italic text-[#4b5563]">No session data available</span>
            )}
          </div>
        </div>

        {/* 7. Executive Summary */}
        <div className="rounded-lg border border-purple-900/30 bg-[#0a0f1a] p-3">
          <div className="mb-1 flex items-center gap-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-[#9ca3af]">
              Executive Summary
            </span>
            {models?.security_intelligence && (
              <AgentBadge agent="security_intelligence" model={models.security_intelligence} />
            )}
          </div>
          <p className="text-sm leading-relaxed text-[#d1d5db]">
            {report.executive_summary}
          </p>
        </div>

        {/* 8. Confidence / Risk / Recommendation */}
        <div className="grid grid-cols-3 gap-4">
          <div className="rounded-lg border border-[#1f2937] bg-[#0a0f1a] p-3">
            <div className="text-xs font-medium uppercase tracking-wider text-[#9ca3af]">
              Confidence
            </div>
            <div className="mt-1 text-2xl font-bold text-[#f3f4f6]">
              {(report.confidence * 100).toFixed(0)}%
            </div>
          </div>

          <div className="rounded-lg border border-[#1f2937] bg-[#0a0f1a] p-3">
            <div className="text-xs font-medium uppercase tracking-wider text-[#9ca3af]">
              Risk Level
            </div>
            <div
              className={`mt-1 text-2xl font-bold ${
                report.risk_level === "LOW"
                  ? "text-green-400"
                  : report.risk_level === "MEDIUM"
                    ? "text-yellow-400"
                    : report.risk_level === "HIGH"
                      ? "text-orange-400"
                      : "text-red-400"
              }`}
            >
              {report.risk_level}
            </div>
          </div>

          <div className="rounded-lg border border-[#1f2937] bg-[#0a0f1a] p-3">
            <div className="text-xs font-medium uppercase tracking-wider text-[#9ca3af]">
              Deployment Recommendation
            </div>
            <div
              className={`mt-1 text-lg font-bold ${
                report.deployment_recommendation === "APPROVE"
                  ? "text-green-400"
                  : report.deployment_recommendation === "APPROVE_WITH_MONITORING"
                    ? "text-yellow-400"
                    : "text-red-400"
              }`}
            >
              {report.deployment_recommendation.replace(/_/g, " ")}
            </div>
          </div>
        </div>

        {/* 9. Findings Summary */}
        <div>
          <h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-[#9ca3af]">
            Findings Summary
          </h4>
          <div className="grid grid-cols-4 gap-3">
            <div className="rounded-lg border border-[#1f2937] bg-[#0a0f1a] p-3">
              <div className="text-xs font-medium uppercase tracking-wider text-[#6b7280]">
                Verified Exploits
              </div>
              <div className="mt-1 text-xl font-bold text-red-400">
                {report.verified_exploits}
              </div>
            </div>
            <div className="rounded-lg border border-[#1f2937] bg-[#0a0f1a] p-3">
              <div className="text-xs font-medium uppercase tracking-wider text-[#6b7280]">
                Speculative Risks
              </div>
              <div className="mt-1 text-xl font-bold text-yellow-400">
                {report.speculative_risks}
              </div>
            </div>
            <div className="rounded-lg border border-[#1f2937] bg-[#0a0f1a] p-3">
              <div className="text-xs font-medium uppercase tracking-wider text-[#6b7280]">
                Informational Findings
              </div>
              <div className="mt-1 text-xl font-bold text-blue-400">
                {report.informational_findings}
              </div>
            </div>
            <div className="rounded-lg border border-[#1f2937] bg-[#0a0f1a] p-3">
              <div className="text-xs font-medium uppercase tracking-wider text-[#6b7280]">
                Audit Recoveries
              </div>
              <div className="mt-1 text-xl font-bold text-purple-400">
                {report.audit_degradations}
              </div>
            </div>
          </div>
        </div>

        {/* 10. Security Intelligence Reasoning */}
        {report.reasoning.length > 0 && (
          <div className="rounded-lg border border-[#1f2937]">
            <button
              type="button"
              onClick={() => setReasoningOpen((v) => !v)}
              className="flex w-full items-center justify-between px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-[#9ca3af] hover:text-[#f3f4f6]"
            >
              <div className="flex items-center gap-2">
                <span>Security Intelligence Reasoning</span>
                {models?.security_intelligence && (
                  <AgentBadge agent="security_intelligence" model={models.security_intelligence} />
                )}
              </div>
              <span
                className={`transition-transform duration-200 ${
                  reasoningOpen ? "rotate-180" : ""
                }`}
              >
                {"\u25BC"}
              </span>
            </button>
            {reasoningOpen && (
              <div className="border-t border-[#1f2937] px-4 py-3">
                <ul className="space-y-1.5">
                  {report.reasoning.map((r, i) => (
                    <li
                      key={i}
                      className="rounded-lg bg-[#0a0f1a] px-3 py-2 text-sm text-[#d1d5db]"
                    >
                      <span className="mr-2 text-[#6b7280]">&bull;</span>
                      {r}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {/* 11. Remaining Risks */}
        <div>
          <h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-[#9ca3af]">
            Remaining Risks
          </h4>
          {report.remaining_risks.length > 0 ? (
            <ul className="space-y-1.5">
              {report.remaining_risks.map((r, i) => (
                <li
                  key={i}
                  className={`rounded-lg px-3 py-2 text-sm ${
                    hasExploits
                      ? "bg-[#3b0a0a] text-red-400"
                      : "bg-[#3b3b0a] text-yellow-400"
                  }`}
                >
                  <span
                    className={`mr-2 ${hasExploits ? "text-red-600" : "text-yellow-600"}`}
                  >
                    &bull;
                  </span>
                  {r}
                </li>
              ))}
            </ul>
          ) : (
            <p className="rounded-lg border border-green-900/30 bg-[#0a3b0a] px-3 py-2 text-sm text-green-400">
              No residual risks identified
            </p>
          )}
        </div>
      </div>
    </div>
  );
};

export default SecurityIntelligenceHero;
