export const EVENT_AGENT: Record<string, { agent: string; abbr: string; color: string; accent: string; bg: string; border: string }> = {
  VULNERABILITY_TRIAGED: {
    agent: "Blue Coder Agent",
    abbr: "BLUE",
    color: "text-blue-400",
    accent: "border-l-blue-500/60",
    bg: "bg-blue-900/10",
    border: "border-blue-900/30",
  },
  PATCH_GENERATED: {
    agent: "Blue Coder Agent",
    abbr: "BLUE",
    color: "text-blue-400",
    accent: "border-l-blue-500/60",
    bg: "bg-blue-900/10",
    border: "border-blue-900/30",
  },
  PATCH_PROPOSED: {
    agent: "Blue Coder Agent",
    abbr: "BLUE",
    color: "text-blue-400",
    accent: "border-l-blue-500/60",
    bg: "bg-blue-900/10",
    border: "border-blue-900/30",
  },
  AUDIT_STARTED: {
    agent: "Red Auditor Agent",
    abbr: "RED",
    color: "text-red-400",
    accent: "border-l-red-500/60",
    bg: "bg-red-900/10",
    border: "border-red-900/30",
  },
  AUDIT_COMPLETED: {
    agent: "Red Auditor Agent",
    abbr: "RED",
    color: "text-red-400",
    accent: "border-l-red-500/60",
    bg: "bg-red-900/10",
    border: "border-red-900/30",
  },
  PATCH_REJECTED: {
    agent: "Red Auditor Agent",
    abbr: "RED",
    color: "text-red-400",
    accent: "border-l-red-500/60",
    bg: "bg-red-900/10",
    border: "border-red-900/30",
  },
  PATCH_ACCEPTED: {
    agent: "Blue Coder Agent",
    abbr: "BLUE",
    color: "text-blue-400",
    accent: "border-l-blue-500/60",
    bg: "bg-blue-900/10",
    border: "border-blue-900/30",
  },
  SECURITY_REPORT_GENERATED: {
    agent: "Security Intelligence Agent",
    abbr: "SI",
    color: "text-purple-400",
    accent: "border-l-purple-500/60",
    bg: "bg-purple-900/10",
    border: "border-purple-900/30",
  },
  MESH_COMPLETED: {
    agent: "System",
    abbr: "SYS",
    color: "text-[#9ca3af]",
    accent: "border-l-gray-500/40",
    bg: "bg-gray-900/10",
    border: "border-gray-900/30",
  },
  MESH_ITERATION: {
    agent: "System",
    abbr: "SYS",
    color: "text-[#9ca3af]",
    accent: "border-l-gray-500/40",
    bg: "bg-gray-900/10",
    border: "border-gray-900/30",
  },
  AGENT_FAILURE: {
    agent: "System",
    abbr: "SYS",
    color: "text-red-400",
    accent: "border-l-red-500/40",
    bg: "bg-red-900/10",
    border: "border-red-900/30",
  },
};

export const DEFAULT_EVENT_STYLE = {
  agent: "System",
  abbr: "SYS",
  color: "text-[#9ca3af]",
  accent: "border-l-gray-500/40",
  bg: "bg-gray-900/10",
  border: "border-gray-900/30",
};

export const HIGHLIGHT_EVENTS = new Set([
  "PATCH_GENERATED",
  "AUDIT_COMPLETED",
  "SECURITY_REPORT_GENERATED",
  "MESH_COMPLETED",
  "AGENT_FAILURE",
]);
