import warnings
from pydantic import BaseModel, Field, model_validator
from typing import List, Optional, Literal

class FileContext(BaseModel):
    file_path: str = Field(..., description="The path of the file inside the repo")
    raw_code: str = Field(..., description="The complete text content of the target file")
    language: str = Field(..., description="Programming language identifier (e.g., 'python', 'javascript')")

class VulnerabilityReport(BaseModel):
    cve_id: Optional[str] = Field(None, description="The CVE identifier if known")
    description: str = Field(..., description="Details regarding the security flaw or bug")
    target_lines: List[int] = Field(..., description="Specific line numbers flagged as insecure")
    severity: str = Field(..., description="Vulnerability impact score: LOW, MEDIUM, HIGH, CRITICAL")

class PatchProposal(BaseModel):
    patch_id: str = Field(..., description="Unique UUID for this specific iteration")
    proposed_code: str = Field(..., description="The completely corrected version of the file content")
    architectural_changes: str = Field(..., description="Clear explanation of the engineering changes made")
    dependencies_added: List[str] = Field(default_factory=list, description="Any external packages required")

class ThoughtNode(BaseModel):
    thought_id: str = Field(..., description="ID of this specific reasoning branch")
    hypothesis: str = Field(..., description="What the auditor is exploring (e.g., 'Testing for SQL injection escape via input truncation')")
    evaluation_result: str = Field(..., description="The outcome of the mental check")
    parent_thoughts: List[str] = Field(default_factory=list, description="IDs of preceding thoughts this node builds upon")

class Evidence(BaseModel):
    file: str = Field(..., description="File path where evidence exists")
    line: int = Field(..., description="Line number of the evidence")
    reason: str = Field(..., description="Explanation of why this evidence supports the finding")

class AuditCritique(BaseModel):
    patch_id: str = Field(..., description="The target patch UUID being scrutinized")
    is_secure: bool = Field(..., description="Explicit true/false flag if the patch passed security review")
    finding_type: Literal["VERIFIED_EXPLOIT", "SPECULATIVE_RISK", "INFORMATIONAL"] = Field(..., description="Classification of the finding: VERIFIED_EXPLOIT if demonstrable from supplied code, SPECULATIVE_RISK if plausible but not demonstrable, INFORMATIONAL for non-blocking recommendations")
    confidence: str = Field(..., description="Confidence level in the finding (e.g., 'HIGH', 'MEDIUM', 'LOW')")
    evidence: List[Evidence] = Field(..., description="Supporting evidence from the supplied code. Empty list if no evidence exists.")
    exploit_found: Optional[str] = Field(None, description="Detailed walkthrough of how the agent broke the patch")
    graph_of_thoughts: List[ThoughtNode] = Field(..., description="The complete GoT reasoning tree generated by DeepSeek-R1")

    @model_validator(mode='after')
    def _downgrade_if_missing_evidence(self):
        if self.finding_type == "VERIFIED_EXPLOIT" and not self.evidence:
            warnings.warn(
                f"Downgrading VERIFIED_EXPLOIT to SPECULATIVE_RISK for patch {self.patch_id}: "
                f"no evidence provided"
            )
            self.finding_type = "SPECULATIVE_RISK"
        return self
